spring:
  profiles:
    active: "dev"

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.yml

  sql:
    init:
      mode: always
      continue-on-error: false
      data-locations: classpath:db/sql/generatedSqlQuery.txt
---
spring:
  config:
    activate:
      on-profile: "dev"
---
spring:
  config:
    activate:
      on-profile: "prod"
---